Flexibility changes
michaeldzjap/Two-Factor-Authentication pull request #3
Opened 2019-04-18 10:12 UTC by kim-dongit

Some changes to improve on flexibility. The documentation will need updating because of this, especially because the migrations are now copied by the publish command. This is a breaking change. On the other hand, it grants users the control they need to adjust to their application.

2019-04-18 11:44 UTC, michaeldzjap commented on src/config/twofactor-auth.php
> +    'enabled' => 'per_user',
I don't really like the idea of mixing strings and booleans here. I'd rather see the three options: "always", "never", "user" or something.

2019-04-18 12:19 UTC, kim-dongit commented
You are right. Made the necessary changes. Also added timestamps to the migration files that get published.

2019-04-18 12:21 UTC, michaeldzjap commented
There's a couple of other things I'd like to see differently. Mostly style related, nothing major. Will comment on those now. But thanks for the PR. Useful additions.

2019-04-18 13:40 UTC, michaeldzjap requested changes

2019-04-18 13:40 UTC, michaeldzjap commented on src/Providers/BaseProvider.php
> +        return $conf === 'always';
Please add a space between the closing `}` of the `if` and the `return` statement

2019-04-18 13:40 UTC, michaeldzjap commented on src/TwoFactorAuthenticable.php
> +        elseif ($enabled === 'always') {
I would prefer to change this to:

```php
$enabled = config('twofactor-auth.enabled', 'per_user');

if ($enabled === 'per_user') {
    $this->twoFactorAuth->update(['id' => $id]);
}

if ($enabled === 'always') {
    $this->upsertTwoFactorAuthId($id);
}

2019-04-18 13:40 UTC, michaeldzjap commented on src/config/twofactor-auth.php
> +    | - 'always': always require two-factor authentication
I would either change the options to: "always" and "never" or "enabled" and "disabled". Whether you go for the first or second I don't really care about.

The options "per_user" I would prefer to see as just "user".

2019-04-18 13:40 UTC, michaeldzjap commented on src/TwoFactorAuthServiceProvider.php
> +        ];
Add a space between `]:` and `$paths`

2019-04-18 13:40 UTC, michaeldzjap commented on src/TwoFactorAuthServiceProvider.php
> +        $paths = [];
Add a space between this line and `foreach`

2019-04-18 13:40 UTC, michaeldzjap commented on src/TwoFactorAuthServiceProvider.php
> +        }
Add a space between the closing `}` of the `foreach` and the next line.

2019-04-18 13:40 UTC, michaeldzjap commented on src/TwoFactorAuthServiceProvider.php
> +            $paths[__DIR__ . '/database/migrations/' . $file] = database_path('migrations/'.date('Y_m_d_His').'_'.$file);
Don't use spaces between each `.`, so make it: `$paths[__DIR__.'/database/migrations/'.$file]`

2019-04-18 13:40 UTC, michaeldzjap commented on src/TwoFactorAuthServiceProvider.php
> +     * Adds current timestamp prefix.
I'd like to see the following docstring:

```php
/**
 * Publish all migration files and prefix them with the current timestamp.
 *
 * @return void
 */
```

2019-04-18 13:40 UTC, michaeldzjap commented on src/config/twofactor-auth.php
> +            'pk' => 'id'
I'd like to have this renamed to "primaryKey" instead of "pk".

2019-04-18 13:40 UTC, michaeldzjap commented on src/TwoFactorAuthenticable.php
> +        return $this->hasOne(TwoFactorAuth::class, $this->getKeyName());
I don't think this is correct. Shouldn't this be:

```php
return $this->hasOne(TwoFactorAuth::class, 'user_id', $this->getKeyName());
```

I.e. the second argument is the foreign key (i.e. "user_id" on the `two_factor_auths` table), the third argument the (custom) primary key.

2019-04-18 13:40 UTC, michaeldzjap commented on src/TwoFactorAuth.php
> +        return $this->belongsTo(\App\User::class, config('twofactor-auth.models.user.pk', 'id'));
I don't think this is correct. Shouldn't this be:

```php
return $this->belongsTo(\App\User::class, 'user_id', config('twofactor-auth.models.user.primaryKey', 'id'));
```

I.e. the second argument is the foreign key (i.e. "user_id" on the two_factor_auths table), the third argument the (custom) primary key.

2019-04-18 13:40 UTC, michaeldzjap commented on src/TwoFactorAuthenticable.php
> +     * @param string $id
I'd like to change the docstring to:

```php
/**
 * Create or update a two-factor authentication record with the given id.
 *
 * @param  string  $id
 * @return void
 */

2019-04-18 13:40 UTC, michaeldzjap commented on src/TwoFactorAuthenticable.php
> +            if (!$this->twoFactorAuth()->exists()) {
Insert a space between the assignment to `$attributes` and the `if` statement.

2019-04-18 13:44 UTC, michaeldzjap commented
Also, it would be good if you could add appropriate tests. There is a separate [test project](https://github.com/michaeldzjap/laravel-two-factor-authentication-example) for this package.

With regards to the breaking changes due to the publishing of the migrations files; this needs to be documented in the README. One problem I foresee is when you already have ran migrations for this package for the main database (and hence, don't want to run them again), but want to run them every time for your test database. I guess wrapping the `Schema::create()` calls inside an `if (environment('test')) {}` check would mitigate this problem.

2019-04-18 15:08 UTC, kim-dongit commented on src/TwoFactorAuthenticable.php
> +        return $this->hasOne(TwoFactorAuth::class, $this->getKeyName());
You are entirely right.

2019-04-19 06:10 UTC, merged

2019-04-19 09:05 UTC, michaeldzjap commented
Just published [v2.4.0](https://github.com/michaeldzjap/laravel-two-factor-authentication/tree/v2.4.0) which includes your additions. Thanks again.

2019-04-23 11:13 UTC, kim-dongit commented
Thank you too. I am not able to look at tests now, but maybe later. What tests do you envision?

2019-04-23 12:40 UTC, michaeldzjap commented
Some unit tests can be added that test the extended "enabled" options. At the moment only the "user" case is tested.

And similarly, some browser (Dusk) tests should really be added that check the extended "enabled" logic works as expected for the "always" and "never" cases.

I don't mind doing this myself, but I don't have much time either at the moment.